version: '3.8'

services:
  api:
    container_name: klaire-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite-data:/data
    env_file:
      - .env
volumes:
  sqlite-data: